"""
屏幕和画布配置信息
"""

# 屏幕尺寸
SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080

# 画布位置
CANVAS_TOP_LEFT = (380, 270)     # 画布左上角坐标
CANVAS_BOTTOM_LEFT = (380, 920)  # 画布左下角坐标

# 计算画布尺寸
CANVAS_WIDTH = SCREEN_WIDTH - (CANVAS_TOP_LEFT[0] * 2)  # 画布宽度
CANVAS_HEIGHT = CANVAS_BOTTOM_LEFT[1] - CANVAS_TOP_LEFT[1]  # 画布高度

# 画布中心点
CANVAS_CENTER = (
    CANVAS_TOP_LEFT[0] + CANVAS_WIDTH // 2,
    CANVAS_TOP_LEFT[1] + CANVAS_HEIGHT // 2
)

# 画布边界
CANVAS_TOP_RIGHT = (SCREEN_WIDTH - CANVAS_TOP_LEFT[0], CANVAS_TOP_LEFT[1])
CANVAS_BOTTOM_RIGHT = (SCREEN_WIDTH - CANVAS_TOP_LEFT[0], CANVAS_BOTTOM_LEFT[1])

# 画与画布的内边距
PAD = 10  # 画布边界与画布内容的间距