# 自动操作相关速度配置
MULTIPLIER_FACTOR = 1.0

BASIC_DRAW_DURATION_1 = 0.5
BASIC_DRAW_DURATION_2 = 0.3
BASIC_DRAW_DURATION_3 = 0.2
BASIC_CLICK_WAIT = 0.5
BASIC_MOUSE_MOVE_SPEED = 0.5
BASIC_EXTRA_MOVE_DELAY = 0.2
